version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get install gcc make
      - run:
          name: make
          command: g++ -Wall -O2 -pipe -march=x86-64 -std=c++14 main.cpp -o esearch
      - run:
          name: Print the Current Time
          command: date
